# -*- coding: utf-8 -*-
"""Etapa_4_modelo_regressão.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThNCFFNbETtpM3kqngPiHYX9wKcdW80I

📋 Avaliação Final — Big Data para Negócios

**Curso:** Big Data para Negócios

**Instituição:** UFC - Universidade Federal do Ceará

**Professor responsável:** Luiz Alexandre Moreira Barros

**Formato:** Individual · Relatório + repositório de código + dashboard

**Aluno(a):** Gabriel Ramos e Thales Vieira

**Data de entrega:** _______________________________________________

Etapa 4 - Modelo de Regressão
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

# 1. LEITURA DA BASE

df = pd.read_csv(
    "/content/avaliacao_transactions.csv",
    parse_dates=["timestamp"]
)

print("\n========== ETAPA 4 - MODELO DE FRAUDE ==========")
print(f"Total de registros: {len(df)}")
print(f"Total de fraudes: {df['is_fraud'].sum()}")
print(f"Taxa de fraude: {(df['is_fraud'].mean() * 100):.2f}%")

# 2. CRIAÇÃO DE VARIÁVEIS TEMPORAIS

df["hora"] = df["timestamp"].dt.hour
df["dia_semana"] = df["timestamp"].dt.dayofweek

# 3. DEFINIÇÃO DAS VARIÁVEIS

features = [
    "amount",
    "risk_score",
    "credit_score",
    "hora",
    "dia_semana",
    "transaction_type",
    "channel",
    "merchant_category",
    "segment"
]

target = "is_fraud"

X = df[features].copy()
y = df[target].astype(int)

# Variáveis numéricas
numeric_features = [
    "amount",
    "risk_score",
    "credit_score",
    "hora",
    "dia_semana"
]

# Variáveis categóricas
categorical_features = [
    "transaction_type",
    "channel",
    "merchant_category",
    "segment"
]

# 4. DIVISÃO ENTRE TREINO E TESTE

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=123,
    stratify=y
)

print("\n--- DIVISÃO DA BASE ---")
print(f"Registros de treino: {len(X_train)}")
print(f"Registros de teste: {len(X_test)}")
print(f"Fraudes no conjunto de teste: {y_test.sum()}")

# 5. PRÉ-PROCESSAMENTO

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numeric_features
        ),
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore",
                drop="first"
            ),
            categorical_features
        )
    ]
)

# 6. MODELO DE REGRESSÃO LOGÍSTICA

modelo = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    random_state=123
)

pipeline = Pipeline(
    steps=[
        ("preprocessamento", preprocessor),
        ("modelo", modelo)
    ]
)

# 7. TREINAMENTO

pipeline.fit(X_train, y_train)

print("\nModelo treinado com sucesso.")

# 8. PROBABILIDADES E PREVISÕES

probabilidades = pipeline.predict_proba(X_test)[:, 1]

threshold = 0.50

previsoes = (
    probabilidades >= threshold
).astype(int)

# 9. MÉTRICAS

auc = roc_auc_score(
    y_test,
    probabilidades
)

matriz = confusion_matrix(
    y_test,
    previsoes
)

tn, fp, fn, tp = matriz.ravel()

precision = precision_score(
    y_test,
    previsoes,
    zero_division=0
)

recall = recall_score(
    y_test,
    previsoes,
    zero_division=0
)

f1 = f1_score(
    y_test,
    previsoes,
    zero_division=0
)

print("\n--- RESULTADOS DO MODELO ---")

print(f"AUC-ROC: {auc:.4f}")
print(f"Threshold utilizado: {threshold:.2f}")

print("\nMatriz de confusão:")
print(matriz)

print("\nLeitura da matriz de confusão:")
print(f"TN - legítimas classificadas corretamente: {tn}")
print(f"FP - legítimas sinalizadas como fraude: {fp}")
print(f"FN - fraudes não identificadas: {fn}")
print(f"TP - fraudes identificadas corretamente: {tp}")

print("\nMétricas da classe fraude:")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")

# 10. INTERPRETAÇÃO DOS COEFICIENTES

encoder = (
    pipeline
    .named_steps["preprocessamento"]
    .named_transformers_["cat"]
)

nomes_categoricos = encoder.get_feature_names_out(
    categorical_features
)

nomes_variaveis = (
    numeric_features
    + list(nomes_categoricos)
)

coeficientes = (
    pipeline
    .named_steps["modelo"]
    .coef_[0]
)

resultado_coeficientes = pd.DataFrame({
    "variavel": nomes_variaveis,
    "coeficiente": coeficientes
})

# Odds Ratio
resultado_coeficientes["odds_ratio"] = np.exp(
    resultado_coeficientes["coeficiente"]
)

# Valor absoluto para ordenar importância
resultado_coeficientes["abs_coef"] = (
    resultado_coeficientes["coeficiente"]
    .abs()
)

resultado_coeficientes = (
    resultado_coeficientes
    .sort_values(
        "abs_coef",
        ascending=False
    )
)

print("\n--- COEFICIENTES DE MAIOR MAGNITUDE ---")

print(
    resultado_coeficientes[
        [
            "variavel",
            "coeficiente",
            "odds_ratio"
        ]
    ]
    .head(15)
    .round(4)
    .to_string(index=False)
)

# 11. MAIORES COEFICIENTES POSITIVOS

positivos = (
    resultado_coeficientes[
        resultado_coeficientes["coeficiente"] > 0
    ]
    .sort_values(
        "coeficiente",
        ascending=False
    )
)

print("\n--- VARIÁVEIS QUE MAIS AUMENTAM A CHANCE ESTIMADA DE FRAUDE ---")

print(
    positivos[
        [
            "variavel",
            "coeficiente",
            "odds_ratio"
        ]
    ]
    .head(10)
    .round(4)
    .to_string(index=False)
)

# 12. MAIORES COEFICIENTES NEGATIVOS

negativos = (
    resultado_coeficientes[
        resultado_coeficientes["coeficiente"] < 0
    ]
    .sort_values(
        "coeficiente",
        ascending=True
    )
)

print("\n--- VARIÁVEIS QUE MAIS REDUZEM A CHANCE ESTIMADA DE FRAUDE ---")

print(
    negativos[
        [
            "variavel",
            "coeficiente",
            "odds_ratio"
        ]
    ]
    .head(10)
    .round(4)
    .to_string(index=False)
)

print("\n========== FIM DA ETAPA 4 ==========")